repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python] 
      
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false