[tool.black]
line-length = 100
target-version = ['py311']
skip-string-normalization = false
src = ['sigma']



[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["sigma"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true


[tool.pytest.ini.options]
python_files="test_*.py"

addopts = "--ds=config.settings.dev"




