# Generated by Django 4.2 on 2024-06-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
