# Generated by Django 4.2 on 2024-07-22 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0001_initial"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_number", models.PositiveIntegerField(null=True)),
                (
                    "questionfield",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ans_status", models.BooleanField(default=False)),
                (
                    "answered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("round_number", models.PositiveIntegerField()),
                ("no_of_questions", models.PositiveIntegerField()),
                ("no_of_schools", models.PositiveIntegerField()),
                ("marks_per_question", models.PositiveIntegerField()),
                ("marks_per_bonus_question", models.PositiveIntegerField()),
                (
                    "quizround",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="quiz.schoolregisteredforquiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="round.question",
                    ),
                ),
                (
                    "roundsub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="round.round"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.school"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="question",
            name="roundquestion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="round.round",
            ),
        ),
        migrations.CreateModel(
            name="bonus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                (
                    "fromschool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fromschool",
                        to="school.school",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="round.question"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="round.round"
                    ),
                ),
                (
                    "toschool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toschool",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
