# Generated by Django 4.2 on 2024-06-21 11:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
        ("round", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundForSchool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_for_schools",
                        to="round.round",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds_for_school",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
