name: Check test and irregular import

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  runtests_linting_and_check_irregular_imports:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check irregular imports
        run: |
          flake8 --max-line-length 100 --ignore=E501 sigma

      - name: Sorting imports in regular order
        run: |
          isort sigma

      - name: Lint folder
        run: |
          black sigma
      
      - name: Apply migrations
        run: |
          python manage.py migrate

      - name: Checks written tests
        run: |
          pytest --ds=config.settings.dev
