name: Check test and irregular import
on:
  workflow_dispatch:

  push:
     branches:
      - '*'
  pull_request:
      branches:
      - '*'
  
jobs:
    runtests_linting_and_check_irregular_imports:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            python-version: 3.11.4
        - name: Install requirements
          run: |
              pip install -r requirements.txt
        - name: Check irregular imports
          run: |
              flake8 --max-line-length 100 sigma
        - name: Sorting imports in regular order
          run: |
              isort sigma
        - name: linting folder
          run: |
              black sigma
        - name: Checks written tests
          run: |
            pytest . 
              

